version: "3"
services:
  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/pizzatech
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
